### ISSUE TITLE
Incorrect context menu

### ISSUE THREAD

**Issue by GibMeMyPacket** [oleg-shilo/shell-x#20]
Hello, 
using `[srt,mkv,mp4]` folder to add context menu for `srt`, `mkv` and `mp4` files.
But it is showing the context menu everywhere!
![image](https://user-images.githubusercontent.com/116040195/213926118-bfa0d6f0-dd1f-4851-8ae2-6551b2b1d995.png)

![image](https://user-images.githubusercontent.com/116040195/213926219-0ad4d1de-9f86-4c07-9f55-088dff129437.png)

**Comment by oleg-shilo** [comment]
I am investigating it. Thank you

**Comment by oleg-shilo** [comment]
Fixed.
I will also address #22 and will release it. (most likely in a day or two)

**Comment by oleg-shilo** [comment]
Published on Chocolatey: https://community.chocolatey.org/packages/shell-x/1.5.3.0

Will be available as soon as Chocolatey moderation is done

**Comment by oleg-shilo** [comment]
Please try now

**Comment by oleg-shilo** [comment]
![image](https://user-images.githubusercontent.com/16729806/226877228-485e41a6-2815-4554-87e4-e56c9f31212c.png)

![image](https://user-images.githubusercontent.com/16729806/226877388-d2c79d23-6e0e-47c9-ada2-efaba1bc43ec.png)

-----

Is it possible that your explorer did not restart after the upgrade?

**Comment by oleg-shilo** [comment]
Strange...
![image](https://user-images.githubusercontent.com/16729806/227199259-5af89112-5011-4998-a404-c8e6702017a9.png)

**Comment by oleg-shilo** [comment]
> Also I noted you still have enabled the [any] folder
Correct. [any] is required to give user convenient access to the shell-x configuration folder:

![image](https://user-images.githubusercontent.com/16729806/227505894-4688edd3-5f11-4a81-b920-e4519a2bee63.png)

Saying that, the dependency on [any] is not intentional. I will address it but until then (as a workaround) please keep [any] enabled.

**Comment by oleg-shilo** [comment]
It is a limitation of the operating system. 
IE you cannot even create a file with such a long name if you are using .NET for that.

![image](https://github.com/oleg-shilo/shell-x/assets/16729806/73356c81-8dee-414f-9fd6-82dc246c6f70)

**Comment by oleg-shilo** [comment]
The MAX_PATH limitation has been known for more than a decade.
Though it's not a universal quality of WIN file system but only one of its subsystems (eg explorer). 
To add even more confusion to this, consider the fact that I have two Win10 systems (different builds) where one has the code above failing to create the file and another one successfully creating it. However in this case the shell extension is failing even to start.

Only some applications, that can act on a very low level of file system can overcome this problem because the limit is imposed on file creation but not renaming (afaik). 

You also can enable Win32 long path support from group policy, providing you have permission.
Then it is expected that all IO libraries will start supporting long-names.

Anyway, Win is still suffering from this problem so its' problematic to address it from the application like shell-x.
