### ISSUE TITLE
JSON configuration

### ISSUE THREAD

**Issue by aminya** [oleg-shilo/shell-x#6]
It would be nice if we can configure the context menu using a JSON file. Something like this:

```json
{
    "txt": {
        "Note editors": {
            "notepad": {
                "command": "notepad.exe %*",
                "image": "notepad.jpg"
            },
            "notepad++": {
                "command": "notepad++.exe %*",
                "image": "notepad++.jpg"
            }
        }
    }
}
```

**Comment by oleg-shilo** [comment]
While I was specifically aiming at simplified file-system based configuration, I think an alternative JSON based config as a benefit.
Making this request into "Enhancement".

It is a simple feature to implement. IE. if `config.json` is present then use it instead of analyzing directory structure.

Due to my work commitment and I engagement to my other OSS projects I don't have capacity to proceed with the feature right now. But will at the first opportunity.

If any one can contribute that would be great too :)
