### ISSUE TITLE
[Request] Support for wildcard with file extensions

### ISSUE THREAD

**Issue by ActualMandM** [oleg-shilo/shell-x#8]
Some file formats might have a `.00` appended to the actual file extension. This is the case with Sonic Unleashed/Generation's AR files.

<img width="192" alt="2021-03-09_20-37-56_explorer" src="https://user-images.githubusercontent.com/15317421/110577405-70b3e200-8117-11eb-9c8e-f869da84954c.png">

Because of this, shell-x won't accept anything under the ar folder, same with ar.00. The folder has to be 00 in order to work.

<img width="664" alt="2021-03-09_20-39-56_explorer" src="https://user-images.githubusercontent.com/15317421/110577517-a6f16180-8117-11eb-99c4-3df78781f42a.png">
<img width="620" alt="2021-03-09_20-40-05_explorer" src="https://user-images.githubusercontent.com/15317421/110577521-a8228e80-8117-11eb-9c2d-119a1961954b.png">
<img width="622" alt="2021-03-09_20-40-18_explorer" src="https://user-images.githubusercontent.com/15317421/110577524-a9ec5200-8117-11eb-993f-a83416cedd2c.png">

Would it be possible to have shell-x have some sort of wildcard feature for cases like these, similar to `ar.*`?

**Comment by oleg-shilo** [comment]
Sorry for such a long delay. My other projects did not give me the space to do it sooner.

=======

Done. 
https://github.com/oleg-shilo/shell-x/releases/tag/v1.3.0.0
It will also be available from Choco as soon as the moderation review is finished

=====

Now you can use wild card. in the config folder names.
Note, since wild card characters are prohibited by the file system you will need to use special characters that looked like the special wold card characters but are in fact special Unicode characters that are safe to use as folder names:

```C#
// The unicode characters that look like ? and * but still allowed in dir and file names
 string safeQuestionMark = "？"; 
 string safeAsterisk = "⁎";
```

Simply copy the characters from this description, compose the desired pattern in the text editor and then paste the pattern in the file explorer as a folder name. 

Thus your desired pattern for files `cmn.ar.00, cmn.ar.01,. . . ` 
will look like this: ` ⁎.ar.⁎`.

**Comment by ActualMandM** [comment]
Thank you!
